# Generated by Django 6.0 on 2026-01-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_rating_product_send_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_hex',
            field=models.CharField(default='#000000', max_length=255),
        ),
    ]
